// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gobenpark/colign/internal/auth (interfaces: APITokenValidator)
//
// Generated by this command:
//
//	mockgen -destination=mock_auth/mock_api_token_validator.go -package=mock_auth github.com/gobenpark/colign/internal/auth APITokenValidator
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPITokenValidator is a mock of APITokenValidator interface.
type MockAPITokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockAPITokenValidatorMockRecorder
	isgomock struct{}
}

// MockAPITokenValidatorMockRecorder is the mock recorder for MockAPITokenValidator.
type MockAPITokenValidatorMockRecorder struct {
	mock *MockAPITokenValidator
}

// NewMockAPITokenValidator creates a new mock instance.
func NewMockAPITokenValidator(ctrl *gomock.Controller) *MockAPITokenValidator {
	mock := &MockAPITokenValidator{ctrl: ctrl}
	mock.recorder = &MockAPITokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPITokenValidator) EXPECT() *MockAPITokenValidatorMockRecorder {
	return m.recorder
}

// ValidateTokenForAuth mocks base method.
func (m *MockAPITokenValidator) ValidateTokenForAuth(ctx context.Context, rawToken string) (int64, string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTokenForAuth", ctx, rawToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ValidateTokenForAuth indicates an expected call of ValidateTokenForAuth.
func (mr *MockAPITokenValidatorMockRecorder) ValidateTokenForAuth(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTokenForAuth", reflect.TypeOf((*MockAPITokenValidator)(nil).ValidateTokenForAuth), ctx, rawToken)
}
